import React from 'react';

function TermsContent() {
  return (
    <div className="terms mb-5">
      <div className="container py-5">
        <div className="terms__card p-3 p-md-5 mx-auto">
          <div className="p-2 p-md-5">
            <h6 className="terms__card--subhead">INTRODUCTION</h6>
            <p className="terms__card--subhead ">
              Welcome to Ennovate Lab.

              Ennovate Lab (“us”, “we”, or “our”) operates ennovatelab.com

              (hereinafter referred to as “Service”).

              Our Privacy Policy governs your visit to ennovatelab.com, and explains
              how we collect, safeguard and disclose information that results from your
              use of our Service.
              We use your data to provide and improve Service. By using Service, you
              agree to the collection and use of information in accordance with this policy.
              Unless otherwise defined in this Privacy Policy, the terms used in this Privacy
              Policy have the same meanings as in our Terms and Conditions.
              Our Terms and Conditions (“Terms”) govern all use of our Service and together
              with the Privacy Policy constitutes your agreement with us (“agreement”).
            </p>
            <h6 className="terms__card--subhead">DEFINATION</h6>
            <p className="terms__card--subhead">
              SERVICE means the ennovatelab.com website operated by Ennovate Lab.

              PERSONAL DATA means data about a living individual who can be identified from those
              data (or from those and other information either in our possession or
              likely to come into our possession).

              USAGE DATA is data collected automatically either generated by the use
              of Service or from Service infrastructure itself (for example,
              the duration of a page visit).

              COOKIES are small files stored on your device (computer or mobile device).

              DATA CONTROLLER means a natural or legal person who (either alone or jointly
              or in common with other persons) determines the purposes for which and the
              manner in which any personal data are, or are to be, processed. For the purpose
              of this Privacy Policy, we are a Data Controller of your data.

              DATA PROCESSORS (OR SERVICE PROVIDERS) means any natural or legal person
              who processes the data on behalf of the Data Controller. We may use the
              services of various Service Providers in order to process your data more effectively.

              DATA SUBJECT is any living individual who is the subject of Personal Data.

              THE USER is the individual using our Service. The User corresponds to the
              Data Subject, who is the subject of Personal Data.

              Information Collection and Use

              We collect several different types of information for various purposes to
              provide and improve our Service to you.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}

export default TermsContent;
